/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV1RouteImport } from './routes/api/v1'
import { Route as ApiV1KitRouteImport } from './routes/api/v1/kit'
import { Route as ApiV1SkillsRouteImport } from './routes/api/v1/skills'
import { Route as ApiV1SkillsIdRouteImport } from './routes/api/v1/skills.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Route = ApiV1RouteImport.update({
  id: '/api/v1',
  path: '/api/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1KitRoute = ApiV1KitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => ApiV1Route,
} as any)
const ApiV1SkillsRoute = ApiV1SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ApiV1Route,
} as any)
const ApiV1SkillsIdRoute = ApiV1SkillsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1SkillsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/api/v1/kit': typeof ApiV1KitRoute
  '/api/v1/skills': typeof ApiV1SkillsRouteWithChildren
  '/api/v1/skills/$id': typeof ApiV1SkillsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/api/v1/kit': typeof ApiV1KitRoute
  '/api/v1/skills': typeof ApiV1SkillsRouteWithChildren
  '/api/v1/skills/$id': typeof ApiV1SkillsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/api/v1/kit': typeof ApiV1KitRoute
  '/api/v1/skills': typeof ApiV1SkillsRouteWithChildren
  '/api/v1/skills/$id': typeof ApiV1SkillsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/v1' | '/api/v1/kit' | '/api/v1/skills' | '/api/v1/skills/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/v1' | '/api/v1/kit' | '/api/v1/skills' | '/api/v1/skills/$id'
  id:
    | '__root__'
    | '/'
    | '/api/v1'
    | '/api/v1/kit'
    | '/api/v1/skills'
    | '/api/v1/skills/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiV1Route: typeof ApiV1RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1': {
      id: '/api/v1'
      path: '/api/v1'
      fullPath: '/api/v1'
      preLoaderRoute: typeof ApiV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/kit': {
      id: '/api/v1/kit'
      path: '/kit'
      fullPath: '/api/v1/kit'
      preLoaderRoute: typeof ApiV1KitRouteImport
      parentRoute: typeof ApiV1Route
    }
    '/api/v1/skills': {
      id: '/api/v1/skills'
      path: '/skills'
      fullPath: '/api/v1/skills'
      preLoaderRoute: typeof ApiV1SkillsRouteImport
      parentRoute: typeof ApiV1Route
    }
    '/api/v1/skills/$id': {
      id: '/api/v1/skills/$id'
      path: '/$id'
      fullPath: '/api/v1/skills/$id'
      preLoaderRoute: typeof ApiV1SkillsIdRouteImport
      parentRoute: typeof ApiV1SkillsRoute
    }
  }
}

interface ApiV1SkillsRouteChildren {
  ApiV1SkillsIdRoute: typeof ApiV1SkillsIdRoute
}

const ApiV1SkillsRouteChildren: ApiV1SkillsRouteChildren = {
  ApiV1SkillsIdRoute: ApiV1SkillsIdRoute,
}

const ApiV1SkillsRouteWithChildren = ApiV1SkillsRoute._addFileChildren(
  ApiV1SkillsRouteChildren,
)

interface ApiV1RouteChildren {
  ApiV1KitRoute: typeof ApiV1KitRoute
  ApiV1SkillsRoute: typeof ApiV1SkillsRouteWithChildren
}

const ApiV1RouteChildren: ApiV1RouteChildren = {
  ApiV1KitRoute: ApiV1KitRoute,
  ApiV1SkillsRoute: ApiV1SkillsRouteWithChildren,
}

const ApiV1RouteWithChildren = ApiV1Route._addFileChildren(ApiV1RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiV1Route: ApiV1RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
